Repository MENDITTZO/DEBOOK_BackEnd, pull requests merged in 2024-11, with the labels that each got.

#3 [setting] #2 백엔드 프로젝트 초기 세팅 업로드
  MENDITTZO-Backend/.gitattributes
  MENDITTZO-Backend/.gitignore
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/gradle/wrapper/gradle-wrapper.jar
  MENDITTZO-Backend/gradle/wrapper/gradle-wrapper.properties
  MENDITTZO-Backend/gradlew
  MENDITTZO-Backend/gradlew.bat
  MENDITTZO-Backend/settings.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/MendittzoBackendApplication.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/CustomException.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorResponse.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/GlobalExceptionHandler.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/SuccessCode.java
  MENDITTZO-Backend/src/main/resources/application.yml
  MENDITTZO-Backend/src/main/resources/static/test.md
  MENDITTZO-Backend/src/main/resources/templates/test.md
  MENDITTZO-Backend/src/test/java/com/mendittzo/MendittzoBackendApplicationTests.java
Labels: ⚙ Setting

#9 setting: #8 application.yml 설정 코드 작성, API-KEY 분리 및 ignore 설정
  MENDITTZO-Backend/.gitignore
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ⚙ Setting

#10 setting: #6 개발 전 설정
  MENDITTZO-Backend/.gitignore
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ⚙ Setting

#16 Feat/elastic/#13 : elastic search 구현
  .idea/.gitignore
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/controller/ElasticController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/dto/ElasticDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/repository/ElasticRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/service/ElasticService.java
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ✨ Feat

#21 chore:#20 elastic search 관련 yml 설정
  MENDITTZO-Backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 💻 Chore

#23 Chore/elastic/#22 log stash 연동
  .env
  .idea/.gitignore
  MENDITTZO-Backend/.gitignore
  MENDITTZO-Backend/logstash/logstash.conf
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/dto/ElasticDTO.java
  MENDITTZO-Backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 💻 Chore

#26 Feat/user : #19 유저 정보 조회/수정 기능 구현
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/SuccessCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/S3Config.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/image/command/service/ImageService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/controller/UserCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/dto/UserUpdateDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/service/UserCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/repository/UserRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/controller/UserQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/dto/UserQueryResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/service/UserQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/domain/repository/UserQueryRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/infrastructure/JpaUserQueryRepository.java
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ✨ Feat

#30 Feat/#24 access, refresh 토큰 생성
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/controller/KakaoLoginController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/dto/DebookTokenDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/dto/TokenCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/dto/UserResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/service/KakaoAuthService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/domain/aggregate/Token.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/domain/repository/TokenRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/infrastructure/repository/JpaTokenRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/mapper/TokenMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorResponse.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/SuccessCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/HMACKeyGenerator.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/JwtUtil.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/controller/UserCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/dto/UserCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/mapper/UserMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/controller/UserQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/dto/UserQueryResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/service/UserQueryService.java
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ✨ Feat

#32 Feat/review: #25 리뷰 생성, 수정, 삭제 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/SuccessCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/controller/ReviewCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/dto/ReviewCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/dto/ReviewUpdateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/service/ReviewCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/domain/aggregate/Review.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/domain/aggregate/ReviewStatus.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/domain/repository/ReviewRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/infrastructure/repository/JpaReviewRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/mapper/ReviewMapper.java
Labels: ✨ Feat

#36 Feat/review: #34 리뷰 조회 기능 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/controller/ReviewCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/dto/ReviewCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/dto/ReviewUpdateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/domain/aggregate/Review.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/controller/ReviewQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewListResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/service/ReviewQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/domain/repository/ReviewQueryRepository.java
Labels: ✨ Feat

#35 feat: #31 redis 연동 완료
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/controller/KakaoAuthController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/dto/AccessTokenResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/dto/RefreshTokenRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/service/KakaoAuthService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/controller/KakaoLoginController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/dto/TokenCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/service/KakaoLoginService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/service/TokenService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/RedisConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/JwtUtil.java
  MENDITTZO-Backend/src/main/resources/application.yml
  docker-compose.yml
Labels: ✨ Feat

#39 Feat/report: #33 신고 횟수에 따른 회원 제재 기능 구현.
  MENDITTZO-Backend/src/main/java/com/mendittzo/MendittzoBackendApplication.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/dto/ReportRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/service/ReportCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/domain/aggregate/Report.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/domain/aggregate/ReportType.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/domain/repository/ReportCommandRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/mapper/ReportMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/restriction/domain/aggregate/RestrictionHistory.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/restriction/domain/aggregate/RestrictionStatus.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/restriction/domain/repository/RestrictionHistoryRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/restriction/infrastructure/repository/JpaRestrictionHistoryRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/restriction/mapper/RestrictionHistoryMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/domain/aggregate/Review.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
Labels: ✨ Feat

#40 Feat/booklist: #37 도서 목록 조회 기능 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/command/domain/aggregate/Book.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/controller/BookListQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookDetailResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookListListResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookListResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/service/BookListQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/domain/repository/BookListRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/domain/repository/ReviewQueryRepository.java
Labels: ✨ Feat

#42 chore/booklist: #41 코드 수정
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/controller/BookListQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookListResponseDTO.java
Labels: 💻 Chore

#44 Feat/#38: 로그인 해서 토큰 넘겨주기
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/controller/KakaoAuthController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/controller/KakaoLoginController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/dto/DebookTokenDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/service/KakaoLoginService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/query/application/service/TokenService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/config/SecurityConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/filter/JwtFilter.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/handler/JwtAccessDeniedHandler.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/handler/JwtAuthenticationEntryPoint.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/service/CustomUserDetails.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/service/userService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/JwtUtil.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/controller/UserQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/dto/UserQueryResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/service/UserQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/domain/repository/UserQueryRepository.java
Labels: ✨ Feat

#47 feat: 프론트에서 보낸 api 요청 헤더에서 토큰 꺼내서 읽기
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/filter/JwtFilter.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/service/userService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/CustomUserDetails.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/JwtUtil.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/util/UserUtil.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/controller/UserQueryController.java
Labels: ✨ Feat

#49 feat/review : #46 내 리뷰 조회 기능 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/service/BookListQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/dto/ReportRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/controller/ReviewCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/dto/ReviewCreateRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/service/ReviewCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/mapper/ReviewMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/controller/ReviewQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewListResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/service/ReviewQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/domain/repository/ReviewQueryRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/controller/UserCommandController.java
Labels: 🔨 Refactor, ✨ Feat

#52 Feat/#48 로그아웃/회원탈퇴 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/controller/KakaoAuthController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/auth/command/application/service/KakaoAuthService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/SuccessCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/config/SecurityConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/controller/UserCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/service/UserCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/repository/UserRepository.java
Labels: ✨ Feat

#57 chore: #55 로그인 여부 확인 코드 수정
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/controller/ReviewQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/service/ReviewQueryService.java
Labels: 💻 Chore

#60 Feat/elasticsearch:#56 스프링 service, config 클래스 구현
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/config/ElasticConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/repository/ElasticRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/service/ElasticService.java
  docker-compose.yml
Labels: ✨ Feat

#61 Feat/review: #59 리뷰 수정을 위한 ReviewDetailResponseDTO 작성
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/controller/ReviewQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewDetailResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/service/ReviewQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/domain/repository/ReviewQueryRepository.java
Labels: ✨ Feat, 💻 Chore

#62 Feat/elasticsearch:#56 nori 적용 및 중복 데이터 제거 작업
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/config/ElasticConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/service/ElasticService.java
  MENDITTZO-Backend/src/test/java/com/mendittzo/elastic/query/service/ElasticServiceTest.java
Labels: ✨ Feat

#64 Feat/commend:#15 도서 추천 챗봇 기능 완료
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/SwaggerConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/service/ChatHistoryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/domain/aggregate/ChatHistory.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/domain/repository/ChatHistoryRepository.java
  MENDITTZO-Backend/src/main/resources/application.yml
Labels: ✨ Feat

#65 Feat/elasticsearch:#56
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/Dockerfile
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/config/ElasticConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/elastic/query/service/ElasticService.java
  docker-compose.yml
Labels: ✨ Feat

#68 feat/chat/#17 채팅 기능 미완성
  MENDITTZO-Backend/build.gradle
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/controller/ChatController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/controller/ChatroomController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/dto/ChatDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/dto/ChatroomDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/service/ChatService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/application/service/ChatroomService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/Chat.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/Chatroom.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/ChatroomStatus.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/ChatroomUserInfo.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/ChatroomUserInfoStatus.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/repository/ChatRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/repository/ChatroomRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/repository/ChatroomUserInfoRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/RedisConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/WebSocketConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/security/config/SecurityConfig.java
Labels: ✨ Feat

#73 Chore: #71 전체적인 코드 수정
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/domain/repository/BookListRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/command/application/controller/ReviewCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewDetailResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/dto/ReviewResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/application/service/ReviewQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/review/query/domain/repository/ReviewQueryRepository.java
  MENDITTZO-Backend/src/test/java/com/mendittzo/booklist/query/application/service/BookListQueryServiceTest.java
  MENDITTZO-Backend/src/test/java/com/mendittzo/review/query/application/service/ReviewQueryServiceTest.java
Labels: 💻 Chore

#75 refactor : #66 userId 호출을 위한 코드 수정 완료
  MENDITTZO-Backend/src/main/java/com/mendittzo/config/GeminiRestTemplateConfig.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/controller/GeminiController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/dto/ChatRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/dto/ChatResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/service/GeminiService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/domain/aggregate/User.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/controller/UserQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/query/application/dto/UserQueryResponseDTO.java
Labels: 🔨 Refactor

#76 feat/elasticsearch:#56 ElasticService Test 코드 작성
  MENDITTZO-Backend/src/test/java/com/mendittzo/elastic/query/service/ElasticServiceTest.java
Labels: ✨ Feat

#77 Chore/report : #70 자잘한 수정, 신고 기능 마무리, 신고 테스트 코드 간단 작성
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/command/domain/aggregate/Book.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/controller/BookListQueryController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/dto/BookResponseDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/application/service/BookListQueryService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/booklist/query/domain/repository/BookListRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/aggregate/Chatroom.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/chat/command/domain/repository/ChatRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/common/exception/ErrorCode.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/controller/ReportCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/dto/ReportRequestDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/application/service/ReportCommandService.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/domain/aggregate/Report.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/domain/repository/ReportCommandRepository.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/report/command/mapper/ReportMapper.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/controller/UserCommandController.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/dto/UserUpdateDTO.java
  MENDITTZO-Backend/src/main/java/com/mendittzo/user/command/application/service/UserCommandService.java
  MENDITTZO-Backend/src/main/resources/application.yml
  MENDITTZO-Backend/src/test/java/com/mendittzo/report/command/application/service/ReportCommandServiceTest.java
Labels: 💻 Chore

#79 chore : #78 도서 추천 챗봇 테스트코드 작성 완료
  MENDITTZO-Backend/src/main/java/com/mendittzo/recommend/command/application/service/GeminiService.java
  MENDITTZO-Backend/src/test/java/com/mendittzo/recommend/command/application/service/GeminiServiceTest.java
Labels: 💻 Chore
